let xmltemplate = `<?xml version="1.0" encoding="UTF-8" ?>
<sheet>
  <whfrpg4e name="Warhammer Fantasy RPG 4th Edition">
    <meta>
    <version>0</version>
    <author></author>
    <contact></contact>
    <notes></notes>
    <released></released>
    <updated></updated>
    </meta>
    <columns>20</columns>
    <section name="basic information">
      <row>1-1</row>
      <col>1-20</col>
      <label>
        <max_chars>16</max_chars>
        <value>basic information</value>
        <format>capitalize</format>
      </label>
      <font>CormorantInfant-Medium.ttf</font>
      <group name="some_group">
        <orientation>row</orientation>
        <field name="basics_name">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>40</size>
          <label>
            <max_chars>16</max_chars>
            <position>last</position>
            <value>name</value>
            <format>capitalize</format>
            <size>40</size>
          </label>
        </field>
        <field name="basics_species">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>20</size>
          <label>
            <max_chars>16</max_chars>
            <position>last</position>
            <value>species</value>
            <format>capitalize</format>
            <size>20</size>
          </label>

        </field>
        <field name="basics_class">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>20</size>
          <label>
            <max_chars>16</max_chars>
            <position>last</position>
            <value>class</value>
            <format>capitalize</format>
            <size>20</size>
          </label>

        </field>
        <field name="basics_career">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>20</size>
          <label>
            <max_chars>16</max_chars>
            <position>last</position>
            <value>career</value>
            <format>capitalize</format>
            <size>20</size>
          </label>

        </field>
        <field name="basics_career_level">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>1</size>
          <label>
            <max_chars>2</max_chars>
            <position>last</position>
            <value>career lvl</value>
            <format>capitalize</format>
            <size>1</size>
          </label>
        </field>
        <field name="basics_career_path">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>1</size>
          <label>
            <max_chars>32</max_chars>
            <position>last</position>
            <value>career path</value>
            <format>capitalize</format>
            <size>1</size>
          </label>
        </field>
        <field name="basics_status">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>1</size>
          <label>
            <max_chars>16</max_chars>
            <position>last</position>
            <value>status</value>
            <format>capitalize</format>
            <size>1</size>
          </label>
        </field>
        <field name="basics_age">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>3</max_chars>
            <position>last</position>
            <value>age</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="basics_height">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>3</max_chars>
            <position>last</position>
            <value>height</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="basics_hair">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>1</size>
          <label>
            <max_chars>12</max_chars>
            <position>last</position>
            <value>hair</value>
            <format>capitalize</format>
            <size>1</size>
          </label>
        </field>
        <field name="basics_eyes">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>text</type>
          <size>5</size>
          <label>
            <max_chars>12</max_chars>
            <position>last</position>
            <value>eyes</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
      </group>
    </section>
    <section name="characteristics">
      <row>2-3</row>
      <col>1-10</col>
      <label>
        <max_chars>16</max_chars>
        <value>characteristics</value>
        <format>uppercase</format>
      </label>
      <group>
        <orientation>row</orientation>
        <field name="ws">
          <values>
            <value></value>
            <value></value>
            <value>"0:ws0+ws1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>ws</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="bs">
          <values>
            <value></value>
            <value></value>
            <value>"0:bs0+bs1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>bs</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="s">
          <values>
            <value></value>
            <value></value>
            <value>"0:s0+s1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>s</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="t">
          <values>
            <value></value>
            <value></value>
            <value>"0:t0+t1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>t</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="i">
          <values>
            <value></value>
            <value></value>
            <value>"0:i0+i1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>i</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="ag">
          <values>
            <value></value>
            <value></value>
            <value>"0:ag0+ag1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>ag</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="dex">
          <values>
            <value></value>
            <value></value>
            <value>"0:dex0+dex1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>dex</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="int">
          <values>
            <value></value>
            <value></value>
            <value>"0:int0+int1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>int</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="wp">
          <values>
            <value></value>
            <value></value>
            <value>"0:wp0+wp1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>wp</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="fel">
          <values>
            <value></value>
            <value></value>
            <value>"0:fel0+fel1"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>fel</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
      </group>
    </section>
    <section name="fate">
      <row>2-2</row>
      <col>11-12</col>
      <label>
        <max_chars>16</max_chars>
        <value>fate</value>
        <format>capitalize</format>
      </label>
      <group>
        <orientation>row</orientation>
        <field name="fate">
          <values>
            <value></value>
          </values>
          <orientation>row</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>fate</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
        <field name="fortune">
          <values>
            <value></value>
          </values>
          <orientation>row</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>fortune</value>
            <format>uppercase</format>
            <size>5</size>
          </label>
        </field>
      </group>
    </section>
    <section name="resilience">
      <row>2-2</row>
      <col>13-15</col>
      <label>
        <max_chars>16</max_chars>
        <value>resilience</value>
        <format>capitalize</format>
      </label>
      <group>
        <orientation>column</orientation>
        <field name="resilience">
          <values>
            <value></value>
          </values>
          <orientation>row</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>resilience</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="resolve">
          <values>
            <value></value>
          </values>
          <orientation>row</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>resolve</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="motivation">
          <values>
            <value></value>
          </values>
          <orientation>row</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>motivation</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
      </group>
    </section>
    <section name="experience">
      <row>2-2</row>
      <col>16-20</col>
      <label>
        <max_chars>16</max_chars>
        <value>experience</value>
        <format>capitalize</format>
      </label>
      <group>
        <orientation>column</orientation>
        <field name="current">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>current</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="spent">
          <values>
            <value></value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>spent</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
        <field name="total">
          <values>
            <value>"0:current-spent"</value>
          </values>
          <orientation>column</orientation>
          <type>number</type>
          <size>5</size>
          <label>
            <max_chars>5</max_chars>
            <position>first</position>
            <value>total</value>
            <format>capitalize</format>
            <size>5</size>
          </label>
        </field>
      </group>
    </section>
  </whfrpg4e>
</sheet>`;